// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yatesocjzqtmqffbjapc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlhdGVzb2NqenF0bXFmZmJqYXBjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUzMjg2OTQsImV4cCI6MjA2MDkwNDY5NH0.X4wHICdzTxxgNMJ_Ois2CQcMN1JljSZeQQYj-x0KQm8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);